version: "3.7"

services:

  app:
    #image: ncr.pub/nyaone/misso:latest
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - hydra
    networks:
      - internal_network
      - external_network
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./.config/misso.yml:/app/config.yml:ro"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - internal_network
    environment:
      POSTGRES_USER: nyaone
      POSTGRES_PASSWORD: "misso+nya.1"
      POSTGRES_DB: hydra
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "./db:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal_network
    volumes:
      - "./redis:/data"

  hydra:
    image: oryd/hydra
    depends_on:
      - db
      - hydra-migrate
    restart: unless-stopped
    ports:
      - "127.0.0.1:4444:4444" # Public port
    networks:
      - internal_network
      - external_network
    volumes:
      - ./.config/hydra.yml:/etc/config/hydra/hydra.yml
    command: serve -c /etc/config/hydra/hydra.yml all

  hydra-migrate:
    image: oryd/hydra
    depends_on:
      - db
    networks:
      - internal_network
    volumes:
      - ./.config/hydra.yml:/etc/config/hydra/hydra.yml
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes

networks:
  internal_network:
    internal: true
  external_network:
