package consts

const (
	TIME_DEFAULT_REQUEST_VALID = 3600 // 1 Hour

	TIME_DEFAULT_LOGIN_REMEMBER   = 600 // 10 Minute
	TIME_DEFAULT_CONSENT_REMEMBER = 0   // Forever

	TIME_DEFAULT_USERINFO_CACHE = 3600 // 1 Hour
)
